version: '3'
services:
  nginx:
    image: nginx:stable
    container_name: nginx-translate
    ports:
      - "10000:10000"
    links:
      - general_zh_en
      - general_en_zh
    networks:
      - "front"
      - "backend"
    volumes: 
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

  general_zh_en:
    image: translate_server_py:latest
    container_name: translate_server_general_zh_en
    expose: 
      - "80"
    networks:
      - "backend"
    volumes:
      - "./general_domain_zh_en:/root/translate_server_py/mount"
    
  general_en_zh:
    image: translate_server_py:latest
    container_name: translate_server_general_en_zh
    expose: 
      - "80"
    networks:
      - "backend"
    volumes:
      - "./general_domain_en_zh:/root/translate_server_py/mount"

networks:
  front:
    driver: bridge
  backend:
    driver: bridge